name: lighthouse-ci demo
on: [push]
jobs:
  lighthouseci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: npm install, build
        run: |
          npm
          npm install -g @lhci/cli@0.8.x
          npm run build
      - name: run lighthouse-ci
        run: |
          lhci collect
          lhci upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}